# Generated by Django 5.0.6 on 2026-05-20 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("org", "Organization"),
                            ("concept", "Concept"),
                            ("place", "Place"),
                            ("event", "Event"),
                            ("product", "Product"),
                            ("other", "Other"),
                        ],
                        default="concept",
                        max_length=16,
                    ),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("predicate", models.CharField(max_length=120)),
                ("weight", models.FloatField(default=1.0)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                (
                    "obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="knowledge.entity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="knowledge.entity",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="accounts.team",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["owner", "kind"], name="knowledge_e_owner_i_820ac5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("owner", "name", "kind")},
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["predicate"], name="knowledge_r_predica_5cd40a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("subject", "predicate", "obj")},
        ),
    ]
